export const countries = [
  { name: "Afghanistan", code: "AF"},
  { name: "Albania", code: "AL"},
  { name: "Algeria", code: "DZ"},
  { name: "Andorra", code: "AD"},
  { name: "Angola", code: "AO"},
  { name: "Argentina", code: "AR"},
  { name: "Armenia", code: "AM"},
  { name: "Australia", code: "AU"},
  { name: "Austria", code: "AT"},
  { name: "Azerbaijan", code: "AZ"},
  { name: "Bahrain", code: "BH"},
  { name: "Bangladesh", code: "BD"},
  { name: "Belgium", code: "BE"},
  { name: "Bolivia", code: "BO"},
  { name: "Brazil", code: "BR"},
  { name: "Bulgaria", code: "BG"},
  { name: "Cambodia", code: "KH"},
  { name: "Cameroon", code: "CM"},
  { name: "Canada", code: "CA"},
  { name: "Chile", code: "CL"},
  { name: "China", code: "CN"},
  { name: "Colombia", code: "CO"},
  { name: "Costa Rica", code: "CR"},
  { name: "Croatia", code: "HR"},
  { name: "Cuba", code: "CU"},
  { name: "Cyprus", code: "CY"},
  { name: "Czech Republic", code: "CZ"},
  { name: "Denmark", code: "DK"},
  { name: "Djibouti", code: "DJ"},
  { name: "Dominican Republic", code: "DO"},
  { name: "Ecuador", code: "EC"},
  { name: "Egypt", code: "EG"},
  { name: "El Salvador", code: "SV"},
  { name: "Estonia", code: "EE"},
  { name: "Ethiopia", code: "ET"},
  { name: "Finland", code: "FI"},
  { name: "France", code: "FR"},
  { name: "Gabon", code: "GA"},
  { name: "Gambia", code: "GM"},
  { name: "Georgia", code: "GE"},
  { name: "Germany", code: "DE"},
  { name: "Ghana", code: "GH"},
  { name: "Greece", code: "GR"},
  { name: "Guatemala", code: "GT"},
  { name: "Haiti", code: "HT"},
  { name: "Honduras", code: "HN"},
  { name: "Hungary", code: "HU"},
  { name: "Iceland", code: "IS"},
  { name: "India", code: "IN"},
  { name: "Indonesia", code: "ID"},
  { name: "Iran", code: "IR"},
  { name: "Iraq", code: "IQ"},
  { name: "Ireland", code: "IE"},
  { name: "Italy", code: "IT"},
  { name: "Ivory Coast", code: "CI"},
  { name: "Jamaica", code: "JM"},
  { name: "Japan", code: "JP"},
  { name: "Jordan", code: "JO"},
  { name: "Kazakhstan", code: "KZ"},
  { name: "Kenya", code: "KE"},
  { name: "Kuwait", code: "KW"},
  { name: "Latvia", code: "LV"},
  { name: "Lebanon", code: "LB"},
  { name: "Libya", code: "LY"},
  { name: "Lithuania", code: "LT"},
  { name: "Luxembourg", code: "LU"},
  { name: "Madagascar", code: "MG"},
  { name: "Malaysia", code: "MY"},
  { name: "Mali", code: "ML"},
  { name: "Malta", code: "MT"},
  { name: "Mauritania", code: "MR"},
  { name: "Mauritius", code: "MU"},
  { name: "Mexico", code: "MX"},
  { name: "Monaco", code: "MC"},
  { name: "Mongolia", code: "MN"},
  { name: "Montenegro", code: "ME"},
  { name: "Morocco", code: "MA"},
  { name: "Netherlands", code: "NL"},
  { name: "New Zealand", code: "NZ"},
  { name: "Norway", code: "NO"},
  { name: "Oman", code: "OM"},
  { name: "Pakistan", code: "PK"},
  { name: "Palestine", code: "PS"},
  { name: "Panama", code: "PA"},
  { name: "Paraguay", code: "PY"},
  { name: "Peru", code: "PE"},
  { name: "Philippines", code: "PH"},
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT"},
  { name: "Qatar", code: "QA"},
  { name: "Romania", code: "RO"},
  { name: "Russia", code: "RU"},
  { name: "Saudi Arabia", code: "SA"},
  { name: "Senegal", code: "SN"},
  { name: "Serbia", code: "RS"},
  { name: "Singapore", code: "SG"},
  { name: "Slovakia", code: "SK"},
  { name: "Slovenia", code: "SI"},
  { name: "South Africa", code: "ZA"},
  { name: "South Korea", code: "KR"},
  { name: "Spain", code: "ES"},
  { name: "Sri Lanka", code: "LK"},
  { name: "Sudan", code: "SD"},
  { name: "Sweden", code: "SE"},
  { name: "Switzerland", code: "CH"},
  { name: "Syria", code: "SY"},
  { name: "Taiwan", code: "TW"},
  { name: "Thailand", code: "TH"},
  { name: "Tunisia", code: "TN"},
  { name: "Turkey", code: "TR"},
  { name: "Ukraine", code: "UA"},
  { name: "United Arab Emirates", code: "AE"},
  { name: "United Kingdom", code: "GB"},
  { name: "United States", code: "US"},
  { name: "Uruguay", code: "UY"},
  { name: "Uzbekistan", code: "UZ"},
  { name: "Venezuela", code: "VE"},
  { name: "Vietnam", code: "VN"},
  { name: "Yemen", code: "YE"}
];
