export const countries = [
  { name: "Afghanistan", code: "AF", emoji: "🇦🇫" },
  { name: "Albania", code: "AL", emoji: "🇦🇱" },
  { name: "Algeria", code: "DZ", emoji: "🇩🇿" },
  { name: "Andorra", code: "AD", emoji: "🇦🇩" },
  { name: "Angola", code: "AO", emoji: "🇦🇴" },
  { name: "Argentina", code: "AR", emoji: "🇦🇷" },
  { name: "Armenia", code: "AM", emoji: "🇦🇲" },
  { name: "Australia", code: "AU", emoji: "🇦🇺" },
  { name: "Austria", code: "AT", emoji: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿" },
  { name: "Bahrain", code: "BH", emoji: "🇧🇭" },
  { name: "Bangladesh", code: "BD", emoji: "🇧🇩" },
  { name: "Belgium", code: "BE", emoji: "🇧🇪" },
  { name: "Bolivia", code: "BO", emoji: "🇧🇴" },
  { name: "Brazil", code: "BR", emoji: "🇧🇷" },
  { name: "Bulgaria", code: "BG", emoji: "🇧🇬" },
  { name: "Cambodia", code: "KH", emoji: "🇰🇭" },
  { name: "Cameroon", code: "CM", emoji: "🇨🇲" },
  { name: "Canada", code: "CA", emoji: "🇨🇦" },
  { name: "Chile", code: "CL", emoji: "🇨🇱" },
  { name: "China", code: "CN", emoji: "🇨🇳" },
  { name: "Colombia", code: "CO", emoji: "🇨🇴" },
  { name: "Costa Rica", code: "CR", emoji: "🇨🇷" },
  { name: "Croatia", code: "HR", emoji: "🇭🇷" },
  { name: "Cuba", code: "CU", emoji: "🇨🇺" },
  { name: "Cyprus", code: "CY", emoji: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", emoji: "🇨🇿" },
  { name: "Denmark", code: "DK", emoji: "🇩🇰" },
  { name: "Djibouti", code: "DJ", emoji: "🇩🇯" },
  { name: "Dominican Republic", code: "DO", emoji: "🇩🇴" },
  { name: "Ecuador", code: "EC", emoji: "🇪🇨" },
  { name: "Egypt", code: "EG", emoji: "🇪🇬" },
  { name: "El Salvador", code: "SV", emoji: "🇸🇻" },
  { name: "Estonia", code: "EE", emoji: "🇪🇪" },
  { name: "Ethiopia", code: "ET", emoji: "🇪🇹" },
  { name: "Finland", code: "FI", emoji: "🇫🇮" },
  { name: "France", code: "FR", emoji: "🇫🇷" },
  { name: "Gabon", code: "GA", emoji: "🇬🇦" },
  { name: "Gambia", code: "GM", emoji: "🇬🇲" },
  { name: "Georgia", code: "GE", emoji: "🇬🇪" },
  { name: "Germany", code: "DE", emoji: "🇩🇪" },
  { name: "Ghana", code: "GH", emoji: "🇬🇭" },
  { name: "Greece", code: "GR", emoji: "🇬🇷" },
  { name: "Guatemala", code: "GT", emoji: "🇬🇹" },
  { name: "Haiti", code: "HT", emoji: "🇭🇹" },
  { name: "Honduras", code: "HN", emoji: "🇭🇳" },
  { name: "Hungary", code: "HU", emoji: "🇭🇺" },
  { name: "Iceland", code: "IS", emoji: "🇮🇸" },
  { name: "India", code: "IN", emoji: "🇮🇳" },
  { name: "Indonesia", code: "ID", emoji: "🇮🇩" },
  { name: "Iran", code: "IR", emoji: "🇮🇷" },
  { name: "Iraq", code: "IQ", emoji: "🇮🇶" },
  { name: "Ireland", code: "IE", emoji: "🇮🇪" },
  { name: "Italy", code: "IT", emoji: "🇮🇹" },
  { name: "Ivory Coast", code: "CI", emoji: "🇨🇮" },
  { name: "Jamaica", code: "JM", emoji: "🇯🇲" },
  { name: "Japan", code: "JP", emoji: "🇯🇵" },
  { name: "Jordan", code: "JO", emoji: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", emoji: "🇰🇿" },
  { name: "Kenya", code: "KE", emoji: "🇰🇪" },
  { name: "Kuwait", code: "KW", emoji: "🇰🇼" },
  { name: "Latvia", code: "LV", emoji: "🇱🇻" },
  { name: "Lebanon", code: "LB", emoji: "🇱🇧" },
  { name: "Libya", code: "LY", emoji: "🇱🇾" },
  { name: "Lithuania", code: "LT", emoji: "🇱🇹" },
  { name: "Luxembourg", code: "LU", emoji: "🇱🇺" },
  { name: "Madagascar", code: "MG", emoji: "🇲🇬" },
  { name: "Malaysia", code: "MY", emoji: "🇲🇾" },
  { name: "Mali", code: "ML", emoji: "🇲🇱" },
  { name: "Malta", code: "MT", emoji: "🇲🇹" },
  { name: "Mauritania", code: "MR", emoji: "🇲🇷" },
  { name: "Mauritius", code: "MU", emoji: "🇲🇺" },
  { name: "Mexico", code: "MX", emoji: "🇲🇽" },
  { name: "Monaco", code: "MC", emoji: "🇲🇨" },
  { name: "Mongolia", code: "MN", emoji: "🇲🇳" },
  { name: "Montenegro", code: "ME", emoji: "🇲🇪" },
  { name: "Morocco", code: "MA", emoji: "🇲🇦" },
  { name: "Netherlands", code: "NL", emoji: "🇳🇱" },
  { name: "New Zealand", code: "NZ", emoji: "🇳🇿" },
  { name: "Norway", code: "NO", emoji: "🇳🇴" },
  { name: "Oman", code: "OM", emoji: "🇴🇲" },
  { name: "Pakistan", code: "PK", emoji: "🇵🇰" },
  { name: "Palestine", code: "PS", emoji: "🇵🇸" },
  { name: "Panama", code: "PA", emoji: "🇵🇦" },
  { name: "Paraguay", code: "PY", emoji: "🇵🇾" },
  { name: "Peru", code: "PE", emoji: "🇵🇪" },
  { name: "Philippines", code: "PH", emoji: "🇵🇭" },
  { name: "Poland", code: "PL", emoji: "🇵🇱" },
  { name: "Portugal", code: "PT", emoji: "🇵🇹" },
  { name: "Qatar", code: "QA", emoji: "🇶🇦" },
  { name: "Romania", code: "RO", emoji: "🇷🇴" },
  { name: "Russia", code: "RU", emoji: "🇷🇺" },
  { name: "Saudi Arabia", code: "SA", emoji: "🇸🇦" },
  { name: "Senegal", code: "SN", emoji: "🇸🇳" },
  { name: "Serbia", code: "RS", emoji: "🇷🇸" },
  { name: "Singapore", code: "SG", emoji: "🇸🇬" },
  { name: "Slovakia", code: "SK", emoji: "🇸🇰" },
  { name: "Slovenia", code: "SI", emoji: "🇸🇮" },
  { name: "South Africa", code: "ZA", emoji: "🇿🇦" },
  { name: "South Korea", code: "KR", emoji: "🇰🇷" },
  { name: "Spain", code: "ES", emoji: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", emoji: "🇱🇰" },
  { name: "Sudan", code: "SD", emoji: "🇸🇩" },
  { name: "Sweden", code: "SE", emoji: "🇸🇪" },
  { name: "Switzerland", code: "CH", emoji: "🇨🇭" },
  { name: "Syria", code: "SY", emoji: "🇸🇾" },
  { name: "Taiwan", code: "TW", emoji: "🇹🇼" },
  { name: "Thailand", code: "TH", emoji: "🇹🇭" },
  { name: "Tunisia", code: "TN", emoji: "🇹🇳" },
  { name: "Turkey", code: "TR", emoji: "🇹🇷" },
  { name: "Ukraine", code: "UA", emoji: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪" },
  { name: "United Kingdom", code: "GB", emoji: "🇬🇧" },
  { name: "United States", code: "US", emoji: "🇺🇸" },
  { name: "Uruguay", code: "UY", emoji: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", emoji: "🇺🇿" },
  { name: "Venezuela", code: "VE", emoji: "🇻🇪" },
  { name: "Vietnam", code: "VN", emoji: "🇻🇳" },
  { name: "Yemen", code: "YE", emoji: "🇾🇪" }
];
